openapi: 3.0.0
info:
  title: Trading Intelligence API
  description: Live crypto trading data
  version: 1.0.0
servers:
  - url: https://titan-trading-2-production.up.railway.app
    description: Production Server

paths:
  /api/positions/bingx:
    get:
      summary: Get Live Positions
      description: Get current BingX trading positions with P&L data
      operationId: getPositions
      responses:
        "200":
          description: Array of trading positions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: XRP/USDT:USDT
                    unrealizedPnl:
                      type: number
                      example: 1286.60
                    side:
                      type: string
                      example: long
                    contracts:
                      type: number
                      example: 824.0
                    entryPrice:
                      type: number
                      example: 1.6341
                    markPrice:
                      type: number
                      example: 3.1956
                    leverage:
                      type: number
                      example: 10.0

  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      responses:
        "200":
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  railway_ready:
                    type: boolean
                    example: true