openapi: 3.1.0
info:
  title: TAAPI.io Basic Plan - All Indicators
  description: Complete access to 200+ technical indicators with 25,000 daily calls. Optimized for Basic plan capabilities.
  version: 1.0.0
servers:
  - url: https://api.taapi.io
paths:
  /rsi:
    get:
      summary: RSI - Relative Strength Index
      operationId: getRSI
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            enum: [binance, bybit, kraken, coinbase, kucoin]
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            enum: [1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M]
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 14
      responses:
        '200':
          description: RSI value (0-100)
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
  /macd:
    get:
      summary: MACD - Moving Average Convergence Divergence
      operationId: getMACD
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: fast
          in: query
          schema:
            type: integer
            default: 12
        - name: slow
          in: query
          schema:
            type: integer
            default: 26
        - name: signal
          in: query
          schema:
            type: integer
            default: 9
      responses:
        '200':
          description: MACD components
          content:
            application/json:
              schema:
                type: object
                properties:
                  valueMACD:
                    type: number
                  valueMACDSignal:
                    type: number
                  valueMACDHist:
                    type: number
  /bbands:
    get:
      summary: Bollinger Bands
      operationId: getBollingerBands
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 20
        - name: stddev
          in: query
          schema:
            type: number
            default: 2
      responses:
        '200':
          description: Bollinger Bands values
          content:
            application/json:
              schema:
                type: object
                properties:
                  valueUpperBand:
                    type: number
                  valueMiddleBand:
                    type: number
                  valueLowerBand:
                    type: number
  /ema:
    get:
      summary: EMA - Exponential Moving Average
      operationId: getEMA
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: EMA value
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
  /sma:
    get:
      summary: SMA - Simple Moving Average
      operationId: getSMA
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: SMA value
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
  /atr:
    get:
      summary: ATR - Average True Range
      operationId: getATR
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 14
      responses:
        '200':
          description: ATR value
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
  /adx:
    get:
      summary: ADX - Average Directional Index
      operationId: getADX
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: period
          in: query
          schema:
            type: integer
            default: 14
      responses:
        '200':
          description: ADX value
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
  /stoch:
    get:
      summary: Stochastic Oscillator
      operationId: getStochastic
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
            default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVlIjoiNjg5NDFjMGE4MDZmZjE2NTFlMmM1ZTM0IiwiaWF0IjoxNzU0NTM3NDUxLCJleHAiOjMzMjU5MDAxNDUxfQ.QRqOzRFsTcYKSYUuezVQMFdJcL2A6lHIwWC5L0JOLTU
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            example: BTC/USDT
        - name: exchange
          in: query
          schema:
            type: string
            default: binance
        - name: interval
          in: query
          schema:
            type: string
            default: 1h
        - name: kPeriod
          in: query
          schema:
            type: integer
            default: 14
        - name: dPeriod
          in: query
          schema:
            type: integer
            default: 3
        - name: slowing
          in: query
          schema:
            type: integer
            default: 3
      responses:
        '200':
          description: Stochastic values
          content:
            application/json:
              schema:
                type: object
                properties:
                  valueK:
                    type: number
                  valueD:
                    type: number