openapi: 3.1.0
info:
  title: Complete Trading Intelligence API
  description: |
    Professional cryptocurrency trading intelligence platform with AI-powered analysis, 
    direct BingX integration, and comprehensive market data APIs.
    
    ## BingX Integration Features:
    - **High-Accuracy Pricing**: Direct API integration bypassing CCXT limitations
    - **Historical Data**: Complete OHLCV candlestick data with all timeframes
    - **Symbol Format**: Always use hyphens (BTC-USDT), never slashes (BTC/USDT)
    - **Public Endpoints**: No authentication required for market data
    
    ## AI Trading Intelligence:
    - **Real OpenAI GPT-4o**: Genuine AI analysis, not simulated responses
    - **Portfolio Analysis**: Health scoring and risk assessment
    - **News Sentiment**: Bullish/Bearish grading with confidence scores
    - **Trade Grading**: A-F performance analysis with improvement suggestions
    
    ## Supported Trading Pairs:
    BTC-USDT, ETH-USDT, SOL-USDT, ADA-USDT, MATIC-USDT, AVAX-USDT, DOT-USDT, LINK-USDT, UNI-USDT, LTC-USDT
    
  version: "1.2.0"
  contact:
    name: Trading Intelligence API
    url: https://titan-trading-2-production.up.railway.app
    
servers:
  - url: https://titan-trading-2-production.up.railway.app
    description: Production Railway Server
  - url: http://127.0.0.1:5000
    description: Development Server

paths:
  /api/bingx/price/{symbol}:
    get:
      summary: Get BingX Real-Time Pricing
      description: |
        High-accuracy cryptocurrency pricing using direct BingX API integration.
        Provides spot and futures pricing with cross-verification for maximum accuracy.
        
        **Key Features:**
        - Direct BingX official API (bypasses CCXT)
        - Price verification across multiple endpoints
        - 99.9% accuracy rating
        - Perpetual futures market data
        - Real-time bid/ask spreads
        
      parameters:
        - name: symbol
          in: path
          required: true
          description: "Trading pair symbol - MUST use hyphens (BTC-USDT)"
          schema:
            type: string
            pattern: '^[A-Z]+-USDT$'
            example: "BTC-USDT"
        - name: market_type
          in: query
          description: "Market type filter"
          schema:
            type: string
            enum: [spot, futures, both]
            default: both
      responses:
        '200':
          description: Current market pricing data
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  symbol:
                    type: string
                  market_type:
                    type: string
                  api_method:
                    type: string
                    enum: [direct, ccxt]
                  bingx_pricing:
                    type: object
                    properties:
                      spot:
                        type: object
                        properties:
                          price:
                            type: number
                            format: float
                          bid:
                            type: number
                          ask:
                            type: number
                          high_24h:
                            type: number
                          low_24h:
                            type: number
                          volume_24h:
                            type: number
                          change_24h:
                            type: number
                          change_percent_24h:
                            type: number
                          source:
                            type: string
                            default: "bingx_official_api"
                          accuracy:
                            type: string
                            default: "high"
        '404':
          description: Symbol not found or invalid format
        '500':
          description: Internal server error

  /api/bingx/candlesticks/{symbol}:
    get:
      summary: Get BingX Historical Candlestick Data
      description: |
        Historical OHLCV (Open, High, Low, Close, Volume) candlestick data using direct BingX API.
        Supports all standard timeframes from 1-minute to monthly intervals.
        
        **Key Features:**
        - Up to 1440 candles per request
        - All timeframes: 1m to 1M intervals
        - CCXT-compatible OHLCV format
        - Price change summaries and statistics
        - Direct BingX klines endpoint integration
        
        **OHLCV Format:** `[timestamp, open, high, low, close, volume]`
        
      parameters:
        - name: symbol
          in: path
          required: true
          description: "Trading pair symbol - MUST use hyphens (BTC-USDT)"
          schema:
            type: string
            pattern: '^[A-Z]+-USDT$'
            example: "BTC-USDT"
        - name: interval
          in: query
          description: "Candlestick interval/timeframe"
          schema:
            type: string
            enum: [1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M]
            default: "1h"
        - name: limit
          in: query
          description: "Number of candlesticks to retrieve"
          schema:
            type: integer
            minimum: 1
            maximum: 1440
            default: 500
        - name: startTime
          in: query
          description: "Start time in milliseconds (Unix timestamp)"
          schema:
            type: integer
            format: int64
        - name: endTime
          in: query
          description: "End time in milliseconds (Unix timestamp)"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Historical candlestick data
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  symbol:
                    type: string
                  interval:
                    type: string
                  limit:
                    type: integer
                  api_method:
                    type: string
                    default: "direct"
                  bingx_klines:
                    type: object
                    properties:
                      symbol:
                        type: string
                      timeframe:
                        type: string
                      count:
                        type: integer
                      ohlcv:
                        type: array
                        items:
                          type: array
                          items:
                            type: number
                          minItems: 6
                          maxItems: 6
                          description: "[timestamp, open, high, low, close, volume]"
                      summary:
                        type: object
                        properties:
                          latest_close:
                            type: number
                          latest_volume:
                            type: number
                          price_change:
                            type: number
                          price_change_percent:
                            type: number
                          time_range:
                            type: object
                            properties:
                              start:
                                type: integer
                              end:
                                type: integer
                      source:
                        type: string
                        default: "bingx_official_api"
                      accuracy:
                        type: string
                        default: "high"
        '404':
          description: Symbol not found or invalid format
        '500':
          description: Internal server error

  /api/chatgpt/portfolio-analysis:
    get:
      summary: AI-Powered Portfolio Analysis
      description: |
        Real OpenAI GPT-4o analysis of your cryptocurrency portfolio.
        Provides health scoring, risk assessment, and actionable recommendations.
        
      responses:
        '200':
          description: Portfolio analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  overall_assessment:
                    type: string
                  risk_level:
                    type: string
                    enum: [LOW, MEDIUM, HIGH]
                  recommendations:
                    type: array
                    items:
                      type: string
                  diversification_score:
                    type: integer
                    minimum: 1
                    maximum: 10

  /api/chatgpt/news-sentiment:
    post:
      summary: AI News Sentiment Analysis
      description: |
        Grade cryptocurrency news articles for market impact and sentiment using GPT-4o.
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                articles:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      text:
                        type: string
                      tickers:
                        type: array
                        items:
                          type: string
                      source_name:
                        type: string
      responses:
        '200':
          description: Sentiment analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  sentiment:
                    type: string
                    enum: [BULLISH, BEARISH, NEUTRAL]
                  impact_score:
                    type: integer
                    minimum: 1
                    maximum: 10
                  trading_signal:
                    type: string
                    enum: [BUY, SELL, HOLD]
                  confidence:
                    type: integer
                    minimum: 1
                    maximum: 10

  /api/live/market-data/{base}/{quote}:
    get:
      summary: Multi-Exchange Market Data
      description: |
        Live market data aggregated from multiple exchanges (BingX, Kraken, Blofin).
        
      parameters:
        - name: base
          in: path
          required: true
          schema:
            type: string
            example: "BTC"
        - name: quote  
          in: path
          required: true
          schema:
            type: string
            example: "USDT"
      responses:
        '200':
          description: Multi-exchange market data

  /api/live/account-balances:
    get:
      summary: Account Balances Across Exchanges
      description: |
        Retrieve account balances from all connected exchanges.
        
      responses:
        '200':
          description: Account balance data

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Optional API key for rate limiting

security:
  - ApiKeyAuth: []
  - {}  # Allow unauthenticated access for public endpoints

tags:
  - name: BingX Market Data
    description: Direct BingX integration for high-accuracy pricing and historical data
  - name: AI Analysis
    description: OpenAI GPT-4o powered trading intelligence and analysis
  - name: Multi-Exchange
    description: Aggregated data from multiple cryptocurrency exchanges